### ISSUE TITLE
Solution seems to be dependent on lib that isn't available

### ISSUE THREAD

**Issue by darrelmiller** [bradygaster/Azure.ApiManagement.IngestTool#1]
Project references an assembly Microsoft.VisualStudio.WindowsAzure.CommonAzureTools.Contracts.1.5  but I can't find it anywhere.

**Comment by mlorbetske** [comment]
@darrelmiller if the file is present on your system, it'd be under C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Windows Azure Tools\Common. If it's not there, changing the reference to use a higher version of the contract should also work.

**Comment by bradygaster-zz** [comment]
Thanks for the help @mlorbetske - should i just 86 the 1.5 reference all-up and go full 1.7?

**Comment by mlorbetske** [comment]
@bradygaster that makes you require a higher version of the Azure SDK - if you want to do that, sure. If not, leaving it as is and updating your reference to point at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Windows Azure Tools\Common\Microsoft.VisualStudio.WindowsAzure.CommonAzureTools.Contracts.1.5.dll should work for any flavor of VS 2015.

**Comment by bradygaster-zz** [comment]
okay @darrelmiller, @mlorbetske shamed me effectively and i've committed a fix for this. try it out. fetch and merge and test it.

**Comment by darrelmiller** [comment]
Thanks for the fix @bradygaster but I believe you need to push the commit too ;-)

**Comment by bradygaster-zz** [comment]
i did. check again. yes @mlorbetske noticed it too. i claim gerbils ate it.

**Comment by darrelmiller** [comment]
@bradygaster Curiously GFW Desktop couldn't see the commits even after I could in the GitHub site.  I had to resort to the COMMAND LINE to be able to pull the changes!

The references are fixed now but I still can't build because it claims that Microsoft.VisualStudio.Services.Client.AccountManagement is not available.  I noticed that my reference to Microsoft.VisualStudio.Services.Client.dll was pointing to a reference from VS2013 and that there is now a nuget package https://www.nuget.org/packages/Microsoft.VisualStudio.Services.Client/14.89.0 for it.  I tried installing this nuget and for some reason it is not referencing the DLL.

**Comment by darrelmiller** [comment]
The Microsoft.VisualStudio.Service.Client.dll is not in the Nuget package release.  Where this DLL comes from is a mystery to me.  What's even more curious is that there are foreign language versions of the docs for the classes https://msdn.microsoft.com/es-es/library/microsoft.visualstudio.services.client.accountmanagement.account.aspx but not English ones :-\

**Comment by bradygaster-zz** [comment]
@darrelmiller i had the same issue. I reached out to Jeff from NuGet about it and we had variant output - when i pulled the NuGet down it lacked the DLL but when he pulled it down it was there. DOWNLOAD the NuGet explicitly, explode it, and drop in what's missing to the packages folder in your project. I know, it's wonky. You also need to have the VS SDK installed - have you verified you have that on your machine?

**Comment by darrelmiller** [comment]
@bradygaster I installed the nuget package manually and that DLL isn't in the Nuget.  In your last commit the hintpath to the DLL points to  
\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\zsj0vlqg.nqk\Microsoft.VisualStudio.Services.Client.dll 

Can you check what extension is in the zsj0vlqg.nqk folder on your machine?

I have the VS Extension tools installed which from what I can tell is synonymous to VS SDK for 2015 https://msdn.microsoft.com/en-us/library/mt683786.aspx

**Comment by bradygaster-zz** [comment]
Numerous contracts are in that folder. Sorry i mentioned the wrong NuGet DUH. That's what i get for typing in meetings [again].
